services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: orenodb
      MYSQL_DATABASE: USER_DB
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '8886:3306'

  redis:
    image: redis:latest
    ports:
      - '16379:6379'

  haproxy:
    image: haproxy:2.3
    ports:
      - '9000:9000'
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  game-server:
    build:
      context: ./GAME_SERVER
      dockerfile: Dockerfile
    ports:
      - '16666:3000' # TCP 게임 서버 포트
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - CLIENT_VERSION=1.0.0
      - DB1_HOST=mysql
      - DB1_PORT=3306
      - DB1_USER=root
      - DB1_PASSWORD=orenodb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis

  lobi-server:
    build:
      context: ./LOBBY_SERVER
      dockerfile: Dockerfile
    ports:
      - '6666:6666' # TCP 로비 서버 포트
    environment:
      - PORT=6666
      - HOST=0.0.0.0
      - CLIENT_VERSION=1.0.0
      - DB1_NAME=USER_DB
      - DB1_HOST=mysql
      - DB1_PORT=3306
      - DB1_USER=root
      - DB1_PASSWORD=orenodb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
      - haproxy

volumes:
  mysql_data:
