services:
  game-server-1:
    build:
      context: ./GAME_SERVER
      dockerfile: Dockerfile
    container_name: game-server-1
    ports:
      - '16666:16666' # TCP 게임 서버 포트
    environment:
      - PORT=16666
      - HOST=3.36.19.101
      - CLIENT_VERSION=1.0.0
      - DB1_NAME=USER_DB
      - DB1_HOST=express-database.c94ueui6qc9r.ap-northeast-2.rds.amazonaws.com
      - DB1_PORT=3306
      - DB1_USER=root
      - DB1_PASSWORD=gLaFmvi38uW4c5z
      - REDIS_HOST=oredis.mmnarf.ng.0001.apn2.cache.amazonaws.com
      - REDIS_PORT=6379

  lobby-server-1:
    build:
      context: ./LOBBY_SERVER
      dockerfile: Dockerfile
    container_name: lobby-server-1
    ports:
      - '6666:6666' # TCP 로비 서버 포트
    environment:
      - PORT=6666
      - HOST=3.36.19.101
      - CLIENT_VERSION=1.0.0
      - DB1_NAME=USER_DB
      - DB1_HOST=express-database.c94ueui6qc9r.ap-northeast-2.rds.amazonaws.com
      - DB1_PORT=3306
      - DB1_USER=root
      - DB1_PASSWORD=gLaFmvi38uW4c5z
      - REDIS_HOST=oredis.mmnarf.ng.0001.apn2.cache.amazonaws.com
      - REDIS_PORT=6379
    deploy:
      resources:
        limits:
          cpus: '0.50' # 최대 1개의 코어 할당
          memory: 256MB # 최대 2GB의 메모리 할당
