services:
  game-server:
    build:
      context: ./gameserver
      dockerfile: Dockerfile
    ports:
      - "16666:3000" # TCP 게임 서버 포트
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=example
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis

  lobi-server:
    build:
      context: ./lobiserver
      dockerfile: Dockerfile
    ports:
      - "6666:3000" # TCP 로비 서버 포트
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=example
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: game
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379" # 레디스 포트가 따로 있나?

volumes:
  mysql_data: