services:
    db:
        image: mysql:8.0
        ports:
            - 3333:3306
        environment:
            MYSQL_DATABASE: test_user
            MYSQL_USER: test
            MYSQL_PASSWORD: test1
            MYSQL_ROOT_PASSWORD: test1
        restart: unless-stopped

