services:
  game-server:
    build:
      context: ./GAME_SERVER
      dockerfile: Dockerfile
    ports:
      - '16666:3000' # TCP 게임 서버 포트
    environment:
      - DB_HOST=mysql
      - DB_PORT=8886
      - DB_USER=root
      - DB_PASSWORD=orenodb
      - REDIS_HOST=16379
    depends_on:
      - mysql
      - redis

  lobi-server:
    build:
      context: ./LOBBY_SERVER
      dockerfile: Dockerfile
    ports:
      - '6666:3000' # TCP 로비 서버 포트
    environment:
      - DB_HOST=mysql
      - DB_PORT=8886
      - DB_USER=root
      - DB_PASSWORD=orenodb
      - REDIS_HOST=16379
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: orenodb
      MYSQL_DATABASE: USER_DB
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '8886:3306'

  redis:
    image: redis:latest
    ports:
      - '16379:6379'

volumes:
  mysql_data:
