import { getCardSum } from '../utils/getCardSum.js';

export const CARD_TYPES = {
  NONE: 0,
  BBANG: 1, // 20장
  BIG_BBANG: 2, // 1장
  SHIELD: 3, // 10장
  VACCINE: 4, // 6장
  CALL_119: 5, // 2장
  DEATH_MATCH: 6, // 4장
  GUERRILLA: 7, // 1장
  ABSORB: 8, // 4장
  HALLUCINATION: 9, // 4장
  FLEA_MARKET: 10, // 3장
  MATURED_SAVINGS: 11, // 2장
  WIN_LOTTERY: 12, // 1장
  SNIPER_GUN: 13, // 1장
  HAND_GUN: 14, // 2장
  DESERT_EAGLE: 15, // 3장
  AUTO_RIFLE: 16, // 2장
  LASER_POINTER: 17, // 1장
  RADAR: 18, // 1장
  AUTO_SHIELD: 19, // 2장
  STEALTH_SUIT: 20, // 2장
  CONTAINMENT_UNIT: 21, // 3장
  SATELLITE_TARGET: 22, // 1장
  BOMB: 23, // 1장
};

export const CARD_TYPES_INDEX = {
  [CARD_TYPES.NONE]: 'NONE',
  [CARD_TYPES.BBANG]: 'BBANG',
  [CARD_TYPES.BIG_BBANG]: 'BIG_BBANG',
  [CARD_TYPES.SHIELD]: 'SHIELD',
  [CARD_TYPES.VACCINE]: 'VACCINE',
  [CARD_TYPES.CALL_119]: 'CALL_119',
  [CARD_TYPES.DEATH_MATCH]: 'DEATH_MATCH',
  [CARD_TYPES.GUERRILLA]: 'GUERRILLA',
  [CARD_TYPES.ABSORB]: 'ABSORB',
  [CARD_TYPES.HALLUCINATION]: 'HALLUCINATION',
  [CARD_TYPES.FLEA_MARKET]: 'FLEA_MARKET',
  [CARD_TYPES.MATURED_SAVINGS]: 'MATURED_SAVINGS',
  [CARD_TYPES.WIN_LOTTERY]: 'WIN_LOTTERY',
  [CARD_TYPES.SNIPER_GUN]: 'SNIPER_GUN',
  [CARD_TYPES.HAND_GUN]: 'HAND_GUN',
  [CARD_TYPES.DESERT_EAGLE]: 'DESERT_EAGLE',
  [CARD_TYPES.AUTO_RIFLE]: 'AUTO_RIFLE',
  [CARD_TYPES.LASER_POINTER]: 'LASER_POINTER',
  [CARD_TYPES.RADAR]: 'RADAR',
  [CARD_TYPES.AUTO_SHIELD]: 'AUTO_SHIELD',
  [CARD_TYPES.STEALTH_SUIT]: 'STEALTH_SUIT',
  [CARD_TYPES.CONTAINMENT_UNIT]: 'CONTAINMENT_UNIT',
  [CARD_TYPES.SATELLITE_TARGET]: 'SATELLITE_TARGET',
  [CARD_TYPES.BOMB]: 'BOMB',
};

export const CARD_LIMIT = {
  [CARD_TYPES.NONE]: 0,
  [CARD_TYPES.BBANG]: 20,
  [CARD_TYPES.BIG_BBANG]: 1,
  [CARD_TYPES.SHIELD]: 10,
  [CARD_TYPES.VACCINE]: 6,
  [CARD_TYPES.CALL_119]: 2,
  [CARD_TYPES.DEATH_MATCH]: 4, // 현피 - 클라 설명서 카드 정보에는 한타로 되어있음
  [CARD_TYPES.GUERRILLA]: 1,
  [CARD_TYPES.ABSORB]: 4,
  [CARD_TYPES.HALLUCINATION]: 4,
  [CARD_TYPES.FLEA_MARKET]: 3,
  [CARD_TYPES.MATURED_SAVINGS]: 2,
  [CARD_TYPES.WIN_LOTTERY]: 1,
  [CARD_TYPES.SNIPER_GUN]: 1,
  [CARD_TYPES.HAND_GUN]: 2,
  [CARD_TYPES.DESERT_EAGLE]: 3,
  [CARD_TYPES.AUTO_RIFLE]: 2,
  [CARD_TYPES.LASER_POINTER]: 1,
  [CARD_TYPES.RADAR]: 1,
  [CARD_TYPES.AUTO_SHIELD]: 2,
  [CARD_TYPES.STEALTH_SUIT]: 2,
  [CARD_TYPES.CONTAINMENT_UNIT]: 3,
  [CARD_TYPES.SATELLITE_TARGET]: 1,
  [CARD_TYPES.BOMB]: 1,
};

export const CARD_SUM = getCardSum(CARD_LIMIT);

export const INIT_DECK = {
  [CARD_TYPES.BBANG]: 5,
  [CARD_TYPES.SHIELD]: 5,
};
